# Introdução


Exemplo de um array Numpy

In [ ]:
import numpy as np


In [7]:
data = [10, 20, 30, 40, 50]
arr = np.array(data)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# Arrays


A função np.array() converte sequências do Python (como listas e tuplas) em objetos ndarray.

In [ ]:
# Vetor 1D a partir de uma lista
vetor = np.array([10, 20, 30, 40])

# Matriz 2D a partir de listas aninhadas
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Definindo o tipo de dado (dtype) explicitamente
array_float = np.array([1, 2, 3], dtype='float32')
array_datas = np.array(['2026-01-01', '2026-02-01'], dtype='datetime64')

print("Vetor:", vetor)
print("Matriz:\n", matriz)
print("Tipos:", array_float.dtype, "|", array_datas.dtype)

Vetor: [10 20 30 40]
Matriz:
 [[1 2 3]
 [4 5 6]]
Tipos: float32 | datetime64[D]



Sequências Numéricas

In [3]:
# Sequência de 0 a 18 com passo de 2
sequencia = np.arange(0, 20, 2)

# 5 valores igualmente espaçados entre 0 e 1
intervalo = np.linspace(0, 1, 5)

print("np.arange:", sequencia)
print("np.linspace:", intervalo)

np.arange: [ 0  2  4  6  8 10 12 14 16 18]
np.linspace: [0.   0.25 0.5  0.75 1.  ]





<br>



**Matrizes de Inicialização e Preenchimento**

In [4]:
# Matriz 2x3 de Zeros
zeros = np.zeros((2, 3))

# Matriz 3x2 de Uns
uns = np.ones((3, 2))

# Matriz 2x2 preenchida com o valor 7
constante = np.full((2, 2), 7)

print("Zeros:\n", zeros)
print("Uns:\n", uns)
print("Constante:\n", constante)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Uns:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Constante:
 [[7 7]
 [7 7]]


<br> Matrizes Quadradas e Diagonais (np.eye e np.identity)

In [5]:
# Matriz Identidade 3x3
identidade = np.identity(3)

# Matriz 3x4 com diagonal de 1s
eye_retangular = np.eye(3, 4)

print("Identidade:\n", identidade)
print("Eye (3x4):\n", eye_retangular)

Identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Eye (3x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


<br> Geração de Dados Aleatórios (np.random)

In [6]:
# Matriz 3x3 de inteiros aleatórios entre 0 e 9
inteiros_rand = np.random.randint(0, 10, size=(3, 3))

# Vetor de 4 floats aleatórios entre 0 e 1
floats_rand = np.random.rand(4)

# Escolha aleatória de elementos
amostra = np.random.choice([10, 20, 30, 40, 50], size=3)

print("Inteiros Aleatórios:\n", inteiros_rand)
print("Floats Aleatórios:", floats_rand)
print("Amostra Aleatória:", amostra)

Inteiros Aleatórios:
 [[1 2 0]
 [5 2 2]
 [9 8 0]]
Floats Aleatórios: [0.87258131 0.46655608 0.49971112 0.73361821]
Amostra Aleatória: [30 50 50]


<br>
**Entendendo o `dtype` no NumPy**

** `dtype`: Conversão para Valores Booleanos (`bool`)**

In [8]:
#import numpy as np

# Array com valores inteiros (incluindo zeros)
dados_num = np.array([0, 1, 5, 0, 10])

# Conversão para tipo booleano
mascara_bool = dados_num.astype(bool)

print("Array original:", dados_num)
print("Array Booleano:", mascara_bool)
print("Tipo de dado:", mascara_bool.dtype)  # Output: bool

Array original: [ 0  1  5  0 10]
Array Booleano: [False  True  True False  True]
Tipo de dado: bool


Trabalhando com Datas e Tempo (datetime64)

In [9]:
#import numpy as np

# Criação de array de datas com precisão diária [D]
datas = np.array(['2026-01-01', '2026-02-01', '2026-03-01'], dtype='datetime64[D]')

# Operação aritmética com datas (adicionando 10 dias)
proximas_datas = datas + np.timedelta64(10, 'D')

print("Datas iniciais:", datas)
print("Datas + 10 dias:", proximas_datas)
print("Tipo de dado:", datas.dtype)  # Output: datetime64[D]

Datas iniciais: ['2026-01-01' '2026-02-01' '2026-03-01']
Datas + 10 dias: ['2026-01-11' '2026-02-11' '2026-03-11']
Tipo de dado: datetime64[D]


#  Dimensões, Shape, Indexação e Slicing no NumPy

**Atributos Estruturais: ndim, shape e size**

**ndim (Número de Dimensões / Eixos)**

In [10]:
# Exemplo 1: Comparando dimensões de diferentes estruturas
vetor = np.array([10, 20, 30])
matriz = np.array([[1, 2], [3, 4]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Vetor ndim:", vetor.ndim)   # Output: 1
print("Matriz ndim:", matriz.ndim) # Output: 2
print("Tensor ndim:", tensor.ndim) # Output: 3

Vetor ndim: 1
Matriz ndim: 2
Tensor ndim: 3


In [11]:
# Exemplo 2: Verificando dimensões após alteração de formato
arr = np.arange(12) # Array 1D com 12 elementos
matriz_respeitada = arr.reshape(3, 4) # Transformado em Matriz 2D (3x4)

print("Array original ndim:", arr.ndim)                # Output: 1
print("Array reformatado ndim:", matriz_respeitada.ndim) # Output: 2

Array original ndim: 1
Array reformatado ndim: 2


**shape (Formato das Dimensões)**

In [12]:
# Exemplo 1: Identificando o formato de vetores e matrizes
vetor = np.array([1, 2, 3, 4, 5])
matriz = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape do vetor:", vetor.shape)   # Output: (5,)  -> 1D com 5 elementos
print("Shape da matriz:", matriz.shape) # Output: (2, 3) -> 2 linhas e 3 colunas

Shape do vetor: (5,)
Shape da matriz: (2, 3)


In [13]:
# Exemplo 2: Trabalhando com matrizes tridimensionais (Tensores)
# Formato: (blocos/fatias, linhas, colunas)
tensor_3d = np.zeros((2, 3, 4))

print("Shape do Tensor 3D:", tensor_3d.shape) # Output: (2, 3, 4)

Shape do Tensor 3D: (2, 3, 4)


**size (Quantidade Total de Elementos)**

In [14]:
# Exemplo 1: Calculando o total de elementos em matrizes
matriz_a = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 = 6 elementos
matriz_b = np.ones((4, 5))                  # 4x5 = 20 elementos

print("Total elementos Matriz A:", matriz_a.size) # Output: 6
print("Total elementos Matriz B:", matriz_b.size) # Output: 20

Total elementos Matriz A: 6
Total elementos Matriz B: 20


In [15]:
# Exemplo 2: Relação entre shape e size em reorganização de dados
dados = np.arange(24)
matriz_4x6 = dados.reshape(4, 6)

# O tamanho total de elementos permanece constante independente do formato
print("Tamanho do vetor original:", dados.size)         # Output: 24
print("Tamanho após reshape (4x6):", matriz_4x6.size)   # Output: 24

Tamanho do vetor original: 24
Tamanho após reshape (4x6): 24


**Indexação (Acesso a Elementos)**

In [16]:
arr_1d = np.array([10, 20, 30, 40, 50])

# Exemplo 1: Acesso simples por índices positivos e negativos
primeiro = arr_1d[0]   # Primeiro elemento (10)
ultimo = arr_1d[-1]    # Último elemento (50)
penultimo = arr_1d[-2] # Penúltimo elemento (40)

print("Primeiro:", primeiro, "| Último:", ultimo, "| Penúltimo:", penultimo)

Primeiro: 10 | Último: 50 | Penúltimo: 40


In [17]:
# Exemplo 2: Acesso múltiplo usando Fancy Indexing (lista de índices)
indices = [0, 2, 4]
subconjunto = arr_1d[indices]

print("Elementos nos índices [0, 2, 4]:", subconjunto) # Output: [10 30 50]

Elementos nos índices [0, 2, 4]: [10 30 50]


** Indexação 2D**

In [18]:
matriz_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Exemplo 1: Acesso direto formato [linha, coluna]
elem_centro = matriz_2d[1, 1] # Segunda linha (índice 1), segunda coluna (índice 1) -> 50
elem_topo_dir = matriz_2d[0, 2] # Primeira linha (índice 0), terceira coluna (índice 2) -> 30

print("Elemento central (1,1):", elem_centro)
print("Topo direito (0,2):", elem_topo_dir)

Elemento central (1,1): 50
Topo direito (0,2): 30


In [19]:
# Exemplo 2: Combinando índices positivos e negativos em matrizes
# Pegando o último elemento da última linha
ultimo_elemento = matriz_2d[-1, -1] # Output: 90

# Pegando o primeiro elemento da última linha
primeiro_ultima_linha = matriz_2d[-1, 0] # Output: 70

print("Último elemento (-1, -1):", ultimo_elemento)
print("Primeiro elemento da última linha (-1, 0):", primeiro_ultima_linha)

Último elemento (-1, -1): 90
Primeiro elemento da última linha (-1, 0): 70


**Slicing (Fatiamento)**

**Slicing 1D**

In [20]:
vetor = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Exemplo 1: Intervalo simples e uso de passo
sub_intervalo = vetor[2:6]     # Do índice 2 ao 5 -> [20, 30, 40, 50]
elementos_pares = vetor[::2]   # Do início ao fim, de 2 em 2 -> [0, 20, 40, 60, 80]

print("Fatia [2:6]:", sub_intervalo)
print("Passo de 2 [::2]:", elementos_pares)

Fatia [2:6]: [20 30 40 50]
Passo de 2 [::2]: [ 0 20 40 60 80]


In [21]:
# Exemplo 2: Omissão de limites e inversão de vetor
primeiros_quatro = vetor[:4]  # Do início até o índice 3 -> [0, 10, 20, 30]
vetor_invertido = vetor[::-1] # Inverte todo o vetor

print("Primeiros 4 elementos [:4]:", primeiros_quatro)
print("Vetor invertido [::-1]:", vetor_invertido)

Primeiros 4 elementos [:4]: [ 0 10 20 30]
Vetor invertido [::-1]: [90 80 70 60 50 40 30 20 10  0]


** Slicing 2D**

In [22]:
matriz = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Exemplo 1: Extraindo submatrizes e colunas completas
submatriz_centro = matriz[1:3, 1:3] # Linhas 1 e 2, Colunas 1 e 2
terceira_coluna = matriz[:, 2]      # Todas as linhas (:), coluna no índice 2

print("Submatriz central 2x2:\n", submatriz_centro)
print("Terceira coluna como vetor 1D:", terceira_coluna)

Submatriz central 2x2:
 [[ 6  7]
 [10 11]]
Terceira coluna como vetor 1D: [ 3  7 11 15]


In [23]:
# Exemplo 2: Seleção alternada de linhas e colunas (com passo)
linhas_pares_colunas_impares = matriz[::2, 1::2]

print("Linhas pares (0, 2) e colunas ímpares (1, 3):\n", linhas_pares_colunas_impares)

Linhas pares (0, 2) e colunas ímpares (1, 3):
 [[ 2  4]
 [10 12]]


**Alteração de Elementos**

**Alteração via Indexação**

In [24]:
# Exemplo 1: Alterando valores individuais em vetor e matriz
vetor = np.array([1, 2, 3, 4])
vetor[0] = 99 # Substitui o primeiro elemento

matriz = np.array([[10, 20], [30, 40]])
matriz[1, 0] = 300 # Substitui o elemento na linha 1, coluna 0

print("Vetor alterado:", vetor)
print("Matriz alterada:\n", matriz)

Vetor alterado: [99  2  3  4]
Matriz alterada:
 [[ 10  20]
 [300  40]]


In [25]:
# Exemplo 2: Atribuição pontual com múltiplos índices
matriz_dados = np.zeros((3, 3), dtype=int)

# Alterando elementos em posições específicas
matriz_dados[0, 0] = 1
matriz_dados[1, 1] = 5
matriz_dados[2, 2] = 9

print("Matriz diagonal alterada:\n", matriz_dados)

Matriz diagonal alterada:
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


**Alteração em Bloco (via Slicing) e o Conceito de View vs Copy**

In [26]:
# Exemplo 1: Alteração em bloco de uma linha ou coluna inteira
matriz = np.array([
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

# Zerando a primeira coluna inteira
matriz[:, 0] = 0

# Substituindo toda a última linha por [99, 99, 99]
matriz[-1, :] = 99

print("Matriz modificada em bloco:\n", matriz)

Matriz modificada em bloco:
 [[ 0 10 10]
 [ 0 20 20]
 [99 99 99]]


In [27]:
# Exemplo 2: Demonstrando o efeito de View vs Cópia explícita (.copy())
original = np.array([1, 2, 3, 4, 5])

# Fatiamento cria uma VIEW (compartilha a mesma memória)
fatia_view = original[1:4]
fatia_view[0] = 999 # Altera também o array original!

print("Original após alterar a VIEW:", original) # Output: [1, 999, 3, 4, 5]

# Para evitar alterar o original, usa-se .copy()
original_preservado = np.array([1, 2, 3, 4, 5])
fatia_copia = original_preservado[1:4].copy()
fatia_copia[0] = 888

print("Original preservado com .copy():", original_preservado) # Output: [1, 2, 3, 4, 5]

Original após alterar a VIEW: [  1 999   3   4   5]
Original preservado com .copy(): [1 2 3 4 5]


#  Operações com Arrays no NumPy

Operações Aritméticas Básicas (+, -, *, /, **)

Operações entre Array e Escalar

In [3]:
#import numpy as np

# Array 1D base
dados = np.array([10, 20, 30, 40])

# Aplicação de operadores com escalares
soma = dados + 5          # [15, 25, 35, 45]
subtracao = dados - 3     # [ 7, 17, 27, 37]
multiplicacao = dados * 2 # [20, 40, 60, 80]
divisao = dados / 4       # [2.5, 5. , 7.5, 10. ]
potencia = dados ** 2     # [100, 400, 900, 1600]

print("Soma (+5):", soma)
print("Subtração (-3):", subtracao)
print("Multiplicação (*2):", multiplicacao)
print("Divisão (/4):", divisao)
print("Potência (**2):", potencia)


Soma (+5): [15 25 35 45]
Subtração (-3): [ 7 17 27 37]
Multiplicação (*2): [20 40 60 80]
Divisão (/4): [ 2.5  5.   7.5 10. ]
Potência (**2): [ 100  400  900 1600]


Operações Aritméticas entre Dois Arrays

In [5]:
#import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Operações par a par (elemento a elemento)
soma_arrays = a + b        # [11, 22, 33, 44]
sub_arrays = b - a         # [ 9, 18, 27, 36]
mult_arrays = a * b        # [10, 40, 90, 160]
div_arrays = b / a         # [10., 10., 10., 10.]
pot_arrays = a ** 2        # [ 1,  4,  9, 16]

print("A + B:", soma_arrays)
print("B - A:", sub_arrays)
print("A * B:", mult_arrays)
print("B / A:", div_arrays)


A + B: [11 22 33 44]
B - A: [ 9 18 27 36]
A * B: [ 10  40  90 160]
B / A: [10. 10. 10. 10.]


Operações Elemento a Elemento (Universal Functions - ufuncs)

Transformações Matemáticas (sqrt, exp, log, sin)

In [6]:
#import numpy as np

valores = np.array([1, 4, 9, 16], dtype=float)

# Aplicação de ufuncs matemáticas
raiz = np.sqrt(valores)     # [1., 2., 3., 4.]
exponencial = np.exp(valores)# [e^1, e^4, e^9, e^16]
logaritmo = np.log(valores) # Logaritmo natural (base e)
seno = np.sin(valores)      # Seno em radianos

print("Raiz Quadrada (np.sqrt):", raiz)
print("Exponencial (np.exp):", exponencial)
print("Logaritmo Natural (np.log):", logaritmo)
print("Seno (np.sin):", seno)


Raiz Quadrada (np.sqrt): [1. 2. 3. 4.]
Exponencial (np.exp): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Logaritmo Natural (np.log): [0.         1.38629436 2.19722458 2.77258872]
Seno (np.sin): [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


Tratamento Numérico (abs, round, floor, ceil)

In [7]:
decimais = np.array([-2.7, -1.2, 0.5, 3.8])

# Funções de arredondamento e valor absoluto
absoluto = np.abs(decimais)   # [2.7, 1.2, 0.5, 3.8]
arredondado = np.round(decimais) # [-3., -1., 0., 4.]
piso = np.floor(decimais)     # Arredonda para baixo: [-3., -2., 0., 3.]
teto = np.ceil(decimais)      # Arredonda para cima:  [-2., -1., 1., 4.]

print("Valor Absoluto (np.abs):", absoluto)
print("Arredondado (np.round):", arredondado)
print("Piso (np.floor):", piso)
print("Teto (np.ceil):", teto)


Valor Absoluto (np.abs): [2.7 1.2 0.5 3.8]
Arredondado (np.round): [-3. -1.  0.  4.]
Piso (np.floor): [-3. -2.  0.  3.]
Teto (np.ceil): [-2. -1.  1.  4.]


Operações entre Arrays: Produto Matricial (@ e np.dot)

Multiplicação Vetor-Vetor e Matriz-Vetor (Produto Escalar)

In [8]:


# Produto Escalar entre dois vetores 1D
v1 = np.array([2, 3])
v2 = np.array([4, 5])
produto_escalar = np.dot(v1, v2)  # (2*4) + (3*5) = 8 + 15 = 23

# Produto entre Matriz (2x3) e Vetor (3,)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
vetor = np.array([1, 0, 2])

resultado_mv = matriz @ vetor # [1*1 + 2*0 + 3*2, 4*1 + 5*0 + 6*2] = [7, 16]

print("Produto Escalar (v1 . v2):", produto_escalar)
print("Matriz (2x3) @ Vetor (3,):", resultado_mv)


Produto Escalar (v1 . v2): 23
Matriz (2x3) @ Vetor (3,): [ 7 16]


Produto Matricial entre Duas Matrizes 2D

In [9]:

# Matriz A (2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matriz B (3x2)
B = np.array([[7, 8],
              [9, 1],
              [2, 3]])

# Produto Matricial A (2x3) x B (3x2) -> Resultado (2x2)
C_operador = A @ B
C_funcao = np.dot(A, B)

print("Matriz A (2x3):\n", A)
print("Matriz B (3x2):\n", B)
print("Produto A @ B (2x2):\n", C_operador)


Matriz A (2x3):
 [[1 2 3]
 [4 5 6]]
Matriz B (3x2):
 [[7 8]
 [9 1]
 [2 3]]
Produto A @ B (2x2):
 [[31 19]
 [85 55]]


**Broadcasting Bem Básico**

Somar um Vetor Linha a Cada Linha de uma Matriz 2D

In [10]:
#import numpy as np

# Matriz 3x3
matriz = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Vetor 1D de 3 elementos
vetor_linha = np.array([1, 2, 3])

# O vetor_linha é somado a CADA uma das 3 linhas da matriz
resultado = matriz + vetor_linha

print("Matriz Original:\n", matriz)
print("Vetor Linha:", vetor_linha)
print("Resultado do Broadcasting:\n", resultado)
# Linha 1: [10+1, 20+2, 30+3] -> [11, 22, 33]
# Linha 2: [40+1, 50+2, 60+3] -> [41, 52, 63]
# Linha 3: [70+1, 80+2, 90+3] -> [71, 82, 93]


Matriz Original:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Vetor Linha: [1 2 3]
Resultado do Broadcasting:
 [[11 22 33]
 [41 52 63]
 [71 82 93]]


Operação entre Vetor Coluna (3, 1) e Vetor Linha (1, 3)

In [11]:
#import numpy as np

# Vetor Coluna (3 linhas, 1 coluna)
coluna = np.array([[10],
                   [20],
                   [30]])

# Vetor Linha (1 linha, 3 colunas)
linha = np.array([1, 2, 3])

# Broadcasting combina as dimensões gerando uma matriz (3, 3)
matriz_gerada = coluna + linha

print("Vetor Coluna (3x1):\n", coluna)
print("Vetor Linha (1x3):", linha)
print("Matriz Gerada via Broadcasting (3x3):\n", matriz_gerada)
# [[10+1, 10+2, 10+3],
#  [20+1, 20+2, 20+3],
#  [30+1, 30+2, 30+3]]


Vetor Coluna (3x1):
 [[10]
 [20]
 [30]]
Vetor Linha (1x3): [1 2 3]
Matriz Gerada via Broadcasting (3x3):
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


# Estatísticas Básicas no NumPy

**Média (np.mean)**

Média simples de um vetor 1D

In [12]:
#import numpy as np

# Notas de um estudante
notas = np.array([7.5, 8.0, 6.5, 9.0, 10.0])

media_notas = np.mean(notas)

print("Notas:", notas)
print("Média final:", media_notas)  # Output: 8.2


Notas: [ 7.5  8.   6.5  9.  10. ]
Média final: 8.2


Sensibilidade da média a valores discrepantes (outliers)

In [13]:
#import numpy as np

# Salários em milhares de reais de uma pequena equipe
salarios = np.array([3.0, 3.5, 4.0, 3.2, 50.0])  # 50.0 é um outlier (diretor)

media_salarios = np.mean(salarios)

print("Salários:", salarios)
print("Média salarial (distorcida pelo outlier):", media_salarios)  # Output: 12.74


Salários: [ 3.   3.5  4.   3.2 50. ]
Média salarial (distorcida pelo outlier): 12.74


**Mediana (np.median)**

Mediana em conjuntos com número ímpar e par de elementos

In [14]:
#import numpy as np

# Conjunto ímpar (o elemento central exato)
impar = np.array([10, 20, 30, 40, 50])
mediana_impar = np.median(impar)  # 30.0

# Conjunto par (média dos dois valores centrais: (20 + 30) / 2)
par = np.array([10, 20, 30, 40])
mediana_par = np.median(par)  # 25.0

print("Mediana (ímpar):", mediana_impar)
print("Mediana (par):", mediana_par)


Mediana (ímpar): 30.0
Mediana (par): 25.0


Comparação entre Média e Mediana na presença de Outliers

In [15]:
#import numpy as np

# Preços de imóveis em centenas de milhares de reais
imoveis = np.array([250, 270, 280, 300, 310, 5000])  # 5000 é uma mansão fora do padrão

print("Média dos preços:", np.mean(imoveis))    # Output: 1068.33 (não reflete a maioria)
print("Mediana dos preços:", np.median(imoveis))  # Output: 290.0 (medida representativa)


Média dos preços: 1068.3333333333333
Mediana dos preços: 290.0


**Desvio Padrão (np.std)**

Medição de dispersão e estabilidade

In [16]:
#import numpy as np

# Desempenho de duas máquinas em produção (em minutos por tarefa)
maquina_A = np.array([10, 10, 10, 10, 10])  # Baixa variabilidade
maquina_B = np.array([2, 18, 5, 15, 10])    # Alta variabilidade

print("Desvio Padrão Máquina A:", np.std(maquina_A))  # Output: 0.0
print("Desvio Padrão Máquina B:", np.std(maquina_B))  # Output: 5.7271...


Desvio Padrão Máquina A: 0.0
Desvio Padrão Máquina B: 5.966573556070519


Desvio Padrão Populacional vs Amostral (ddof)

In [17]:
#import numpy as np

dados = np.array([12, 15, 18, 20, 25])

# Por padrão, np.std usa ddof=0 (Desvio Padrão Populacional: N no denominador)
std_populacional = np.std(dados)

# Com ddof=1, calcula o Desvio Padrão Amostral (N - 1 no denominador)
std_amostral = np.std(dados, ddof=1)

print("Std Populacional (ddof=0):", std_populacional)  # Output: 4.4271...
print("Std Amostral (ddof=1):", std_amostral)          # Output: 4.9497...


Std Populacional (ddof=0): 4.427188724235731
Std Amostral (ddof=1): 4.949747468305833


**Variância (np.var)**

Relação matemática entre Variância e Desvio Padrão

In [18]:
#import numpy as np

temperaturas = np.array([22.5, 24.0, 21.0, 25.5, 23.0])

variancia = np.var(temperaturas)
desvio_padrao = np.std(temperaturas)

print("Variância:", variancia)                      # Output: 2.3
print("Desvio Padrão:", desvio_padrao)              # Output: 1.5165...
print("Raiz quadrada da Variância:", np.sqrt(variancia))  # Igual ao desvio padrão!


Variância: 2.2600000000000002
Desvio Padrão: 1.503329637837291
Raiz quadrada da Variância: 1.503329637837291


Variância amostral (ddof=1)

In [19]:
#import numpy as np

amostra_vendas = np.array([100, 120, 110, 150, 130])

var_amostral = np.var(amostra_vendas, ddof=1)

print("Variância Amostral:", var_amostral)  # Output: 370.0


Variância Amostral: 370.0


**Mínimo e Máximo (np.min e np.max)**

Cálculo da Amplitude Térmica (max - min)

In [20]:
#import numpy as np

temperaturas_dia = np.array([14.2, 18.5, 25.0, 28.4, 21.1, 16.0])

minimo = np.min(temperaturas_dia)
maximo = np.max(temperaturas_dia)
amplitude = maximo - minimo

print(f"Mínima: {minimo}°C | Máxima: {maximo}°C")
print(f"Amplitude Térmica: {amplitude}°C")  # Output: 14.2°C


Mínima: 14.2°C | Máxima: 28.4°C
Amplitude Térmica: 14.2°C


Encontrando limites em uma Matriz 2D

In [21]:
#import numpy as np

matriz_imagem = np.array([
    [12, 150, 200],
    [0,  255, 180],
    [45,  90, 210]
])

print("Pixel de menor intensidade:", np.min(matriz_imagem))  # Output: 0
print("Pixel de maior intensidade:", np.max(matriz_imagem))  # Output: 255


Pixel de menor intensidade: 0
Pixel de maior intensidade: 255


**Soma (np.sum)**

Soma Total e Soma Acumulada (np.cumsum)

In [22]:
#import numpy as np

vendas_diarias = np.array([100, 150, 200, 80, 120])

soma_total = np.sum(vendas_diarias)
soma_acumulada = np.cumsum(vendas_diarias)  # Evolução do faturamento dia a dia

print("Faturamento Total:", soma_total)          # Output: 650
print("Faturamento Acumulado:", soma_acumulada)  # Output: [100, 250, 450, 530, 650]


Faturamento Total: 650
Faturamento Acumulado: [100 250 450 530 650]


Soma de Condições Booleanas (Contagem de Ocorrências)


In [23]:
#import numpy as np

idades = np.array([15, 22, 17, 30, 18, 12, 45])

# Expressão booleana retorna [False, True, False, True, True, False, True]
maiores_de_idade = idades >= 18

# np.sum trata True como 1 e False como 0
total_maiores = np.sum(maiores_de_idade)

print("Total de maiores de idade:", total_maiores)  # Output: 4


Total de maiores de idade: 4


**Índices de Mínimo e Máximo (np.argmin e np.argmax)**

Localizando posições críticas em Vetores 1D


In [24]:
#import numpy as np

precos_acao = np.array([45.0, 42.5, 39.0, 48.0, 51.5, 40.0])

idx_menor_preco = np.argmin(precos_acao)
idx_maior_preco = np.argmax(precos_acao)

print(f"Dia de compra ideal (Menor preço): Dia {idx_menor_preco} (R$ {precos_acao[idx_menor_preco]})")
print(f"Dia de venda ideal (Maior preço): Dia {idx_maior_preco} (R$ {precos_acao[idx_maior_preco]})")


Dia de compra ideal (Menor preço): Dia 2 (R$ 39.0)
Dia de venda ideal (Maior preço): Dia 4 (R$ 51.5)


 Localização de elemento em Matriz 2D com np.unravel_index

In [25]:
#import numpy as np

matriz_vendas = np.array([
    [100, 250, 300],
    [400, 150, 600],
    [200, 350, 120]
])

# argmax em matriz 2D retorna o índice 'achatado' (flattened)
idx_achatado = np.argmax(matriz_vendas)  # Output: 5

# Converte o índice achatado na coordenada (linha, coluna)
coordenada = np.unravel_index(idx_achatado, matriz_vendas.shape)

print("Índice achatado do ponto máximo:", idx_achatado)
print("Coordenada (linha, coluna) do ponto máximo:", coordenada)  # Output: (1, 2)


Índice achatado do ponto máximo: 5
Coordenada (linha, coluna) do ponto máximo: (np.int64(1), np.int64(2))


**Operações ao Longo dos Eixos (axis=0 e axis=1)**

Agregação por Colunas vs Agregação por Linhas

In [26]:
#import numpy as np

# Matriz 3x3: Linhas = Alunos | Colunas = Provas (P1, P2, P3)
notas_turma = np.array([
    [8.0, 7.0, 9.0],  # Aluno 0
    [5.0, 6.0, 4.0],  # Aluno 1
    [10.0, 9.5, 9.0]  # Aluno 2
])

# Média de cada prova (ao longo das colunas -> axis=0)
media_provas = np.mean(notas_turma, axis=0)

# Média de cada aluno (ao longo das linhas -> axis=1)
media_alunos = np.mean(notas_turma, axis=1)

print("Média por prova (P1, P2, P3):", media_provas)  # Output: [7.666..., 7.5, 7.333...]
print("Média por aluno (Aluno 0, 1, 2):", media_alunos) # Output: [8.0, 5.0, 9.5]


Média por prova (P1, P2, P3): [7.66666667 7.5        7.33333333]
Média por aluno (Aluno 0, 1, 2): [8.  5.  9.5]


Preservando a Estrutura Multidimensional com keepdims=True

In [27]:
#import numpy as np

matriz = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Sem keepdims: resultado é um vetor 1D de shape (2,)
soma_sem_keep = np.sum(matriz, axis=1)

# Com keepdims=True: mantém a dimensão 2D com shape (2, 1), facilitando o broadcasting futuro
soma_com_keep = np.sum(matriz, axis=1, keepdims=True)

print("Soma sem keepdims (shape):", soma_sem_keep.shape, "->", soma_sem_keep)
print("Soma com keepdims (shape):", soma_com_keep.shape, "->\n", soma_com_keep)


Soma sem keepdims (shape): (2,) -> [ 60 150]
Soma com keepdims (shape): (2, 1) ->
 [[ 60]
 [150]]


# Referências

**Referências**


Bisht, K. S. (2022). NumPy: From Basic to Advance.

Idris, I. (2014). Learning NumPy Array. Packt Publishing.

Khonprakhon, S. (2023). NumPy Mastery: 150 Practical Examples in Python.

NumPy Documentation. NumPy Official Technical Manuals and User Guides.

Sohail, M. (2025). NumPy for Data Analysis and Data Science: A Complete Guide.

Yildiz, M. (2024). Mastering NumPy: The Ultimate Guide to Data Manipulation in Python.